# Generated by Django 5.2.4 on 2025-08-08 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
